nelmio_api_doc:
    documentation:
        info:
            title: Weather App
            description: This is an app to fetch weather from OpenWeatherMap
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc(\.json)?$) # Accepts routes under /api except /api/doc
