php:
  build: ./.docker/php72/
  command: bash -c "cd /app && /app/.docker/php72/init.sh && php -S 0.0.0.0:80 -t /app/public"
  ports:
    - "80:80"
  volumes:
    - ./:/app
  container_name: php_weather
  environment:
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: weather_app
  links:
    - "mysql:mysql"

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  volumes:
    - ./.docker/mysql/data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: weather_app
  container_name: mysql_weather
